name: TestWorkFlow

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.17.2'

      - name: Build app
        env: 
          WHO_TO_TRUST: ${{ secrets.TELEGRAM_API }}
        run: |
          echo "$WHO_TO_TRUST"
          echo ${{ secrets.TELEGRAM_API }}
          go build
          ./birthday-telegram-bot
          