name: TestWorkFlow

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.17.2'

      - name: Build app
        env: 
          TELEGRAM_API: ${{ secrets.TELEGRAM_API }}
          MESSAGE_ID: ${{ secrets.MESSAGE_ID }}
          NAMEDAYS: ${{ secrets.NAMEDAYS }}
          BIRTHDAYS: ${{ secrets.BIRTHDAYS }}
        run: |
          printf "$NAMEDAYS" > nameday
          #echo -e $BIRTHDAYS > birthday

          #go build
          #./birthday-telegram-bot ./nameday ./birthday    
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: NAMEDAYS
          path: nameday